import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export type PdfStudentRow = {
  serial: number;
  name: string;
  ruid: string;
  email: string;
  status?: string | null;
};

export type PdfMeta = {
  title: string;
  subtitle?: string;
  subjectName: string;
  facultyName: string;
  sectionName: string;
  date?: string;
  summary?: { total: number; present: number; absent: number };
};

function statusLabel(s?: string | null) {
  if (s === "present") return "Present";
  if (s === "absent") return "Absent";
  return "Not Marked";
}

/** Generates a formatted, multi-page student/attendance PDF. */
export function generateStudentPdf(
  filename: string,
  meta: PdfMeta,
  rows: PdfStudentRow[],
  opts: { includeStatus?: boolean } = {},
) {
  const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(13, 60, 110);
  doc.text(meta.title, pageWidth / 2, 48, { align: "center" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(80);
  if (meta.subtitle) doc.text(meta.subtitle, pageWidth / 2, 66, { align: "center" });

  const infoY = 92;
  doc.setFontSize(10);
  doc.setTextColor(40);
  const info = [
    `Subject: ${meta.subjectName}`,
    `Faculty: ${meta.facultyName}`,
    `Section: ${meta.sectionName}`,
    `Date: ${meta.date ?? new Date().toLocaleDateString()}`,
  ];
  info.forEach((line, i) => doc.text(line, 40 + i * (pageWidth - 80) / 4, infoY));

  let startY = infoY + 14;
  if (meta.summary) {
    doc.setFont("helvetica", "bold");
    doc.text(
      `Total: ${meta.summary.total}    Present: ${meta.summary.present}    Absent: ${meta.summary.absent}`,
      40,
      startY + 6,
    );
    doc.setFont("helvetica", "normal");
    startY += 18;
  }

  const head = opts.includeStatus
    ? [["S.No.", "Student Name", "RUID", "Email", "Status"]]
    : [["S.No.", "Student Name", "RUID", "Email"]];
  const body = rows.map((r) =>
    opts.includeStatus
      ? [String(r.serial), r.name, r.ruid, r.email, statusLabel(r.status)]
      : [String(r.serial), r.name, r.ruid, r.email],
  );

  autoTable(doc, {
    head,
    body,
    startY,
    margin: { left: 40, right: 40 },
    styles: { fontSize: 9, cellPadding: 5 },
    headStyles: { fillColor: [13, 75, 143], textColor: 255 },
    alternateRowStyles: { fillColor: [244, 248, 252] },
    columnStyles: { 0: { cellWidth: 44, halign: "center" } },
    didParseCell: (data) => {
      if (opts.includeStatus && data.section === "body" && data.column.index === 4) {
        const v = String(data.cell.raw);
        if (v === "Present") data.cell.styles.textColor = [22, 128, 61];
        else if (v === "Absent") data.cell.styles.textColor = [185, 28, 28];
      }
    },
    didDrawPage: () => {
      const pageCount = doc.getNumberOfPages();
      doc.setFontSize(8);
      doc.setTextColor(120);
      doc.text(
        `Page ${doc.getCurrentPageInfo().pageNumber} of ${pageCount}`,
        pageWidth - 40,
        doc.internal.pageSize.getHeight() - 20,
        { align: "right" },
      );
      doc.text("Generated by EIT Student Directory", 40, doc.internal.pageSize.getHeight() - 20);
    },
  });

  doc.save(filename);
}
